### ISSUE TITLE
Deaddead  link https://github.com/alexa/alexa-cookbook/tree/master/testing/postman/README.md

### ISSUE THREAD

**Issue by jerzy-wachowiak** [alexa-samples/skill-sample-nodejs-quiz-game#54]
Unit Testing with Alexa  (https://github.com/alexa/alexa-cookbook/tree/master/testing/postman/README.md points to 404 on the page https://github.com/alexa/skill-sample-nodejs-quiz-game/blob/master/instructions/test-using-simulator.md

**Comment by aszk** [comment]
Closing. The link has been removed from the page.
